### ISSUE TITLE
code within the repository is not sufficient to run

### ISSUE THREAD

**Issue by klaernie** [badele/pelicanthemes-generator#1]
Hi Bruno,

I appreciate the work you did to grab screenshots of every theme, but there are some documentation and instructions missing:
- there is no `make all` target, and the `themes` target is not the first one, so running just `make` will result in an error message
- all makefiles are non-phony: `.PHONY: html confs articles screenshots themes serve push upload` should be in there
- there are no instructions on the dependencies (`CubyCapt` needs to be installed, binary name might differ - `cubycapt` on Debian).
- CubyCapt might not support `--max-width=1024 --max-height=2048`
- the directories that need to be present are never created and not contained in the repository (`touch .gitkeep`)
  - output
  - content
  - content/static
  - confs
- ignoring themes shouldn't be done in a manual list, rather:
  - load ignored themes from a central file, with explanation why it is ignored
  - try to generate any theme that is present, and raise an exception. This ensures that all existing and working themes will be built
- Ideally also the pelican-themes repository should be submodule'd into a directory, and that destination used throughout the repository.

Thanks and kind regards,
Andre

**Comment by badele** [comment]
Hi,
I applied some changes.
- I'm not a expert in this makefile configuration, i have juste updated makefile
- In my previous cutycapt executable, we have a --max-with option, i have remove, because it seem not used now.
- I create directories before execute scripts
- I have added a try/catch exceptions
